export { default as AbstractSwapProtocol } from "./abstract-swap-protocol.js";
export { default as AbstractBridgeProtocol } from "./abstract-bridge-protocol.js";
export { default as AbstractLendingProtocol } from "./abstract-lending-protocol.js";
export type SwapProtocolConfig = import("./abstract-swap-protocol.js").SwapProtocolConfig;
export type SwapOptions = import("./abstract-swap-protocol.js").SwapOptions;
export type SwapResult = import("./abstract-swap-protocol.js").SwapResult;
export type BridgeProtocolConfig = import("./abstract-bridge-protocol.js").BridgeProtocolConfig;
export type BridgeOptions = import("./abstract-bridge-protocol.js").BridgeOptions;
export type BridgeResult = import("./abstract-bridge-protocol.js").BridgeResult;
export type SupplyOptions = import("./abstract-lending-protocol.js").SupplyOptions;
export type SupplyResult = import("./abstract-lending-protocol.js").SupplyResult;
export type WithdrawOptions = import("./abstract-lending-protocol.js").WithdrawOptions;
export type WithdrawResult = import("./abstract-lending-protocol.js").WithdrawResult;
export type BorrowOptions = import("./abstract-lending-protocol.js").BorrowOptions;
export type BorrowResult = import("./abstract-lending-protocol.js").BorrowResult;
export type RepayOptions = import("./abstract-lending-protocol.js").RepayOptions;
export type RepayResult = import("./abstract-lending-protocol.js").RepayResult;
